### ISSUE TITLE
connect is not defined

### ISSUE THREAD

**Issue by sreedhar85in** [cactuz/cors-tester-from-browser#1]
When running the command "node server.js", we get the following error,

D:\Sreedhar\mata>node server.js
D:\Sreedhar\mata\server.js:2
   connect().use(serveStatic(__dirname)).listen(8089, function(){
   ^

ReferenceError: connect is not defined
    at Object.<anonymous> (D:\Sreedhar\mata\server.js:2:4)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

This is because the connect is not defined as a variable in the server.js file.

But even though the readme.md file contains the variable declaration, the formatting is not proper due to which the first line doesnt appear when we read the readme.md file directly in the github.

Please see the screenshot where you cannot see the first line "var connect = require('connect')"  inside the github reading page.

![image](https://user-images.githubusercontent.com/38508108/87889997-960cb680-ca88-11ea-8cf7-7bae5dc69dba.png)

**Comment by sreedhar85in** [comment]
This issue is fixed
